#配置数据源
spring:
  datasource:
     url: jdbc:mysql://127.0.0.1:3306/skeyedu
     username: root
    password: root
     driver-class-name: com.mysql.jdbc.Driver

#指定mybatis映射文件的地址
mybatis:
  mapper-locations: classpath:com/example/demo/mapper/*.xml
